pipeline {
    agent any
    environment {
        HOME = '.'
        PROJECT = "zeronetdev/rampup-back"
        container = null
        failed_stage = null
    }
    stages {
        stage("test"){
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'npm install'
                sh 'npm test'
                junit '**/test-results.xml'
            }
            post {
                failure {
                    script {
                        failed_stage = "test"
                    }
                }
            }
        }
        stage("build back image"){
            steps {
                script {
                    container = docker.build(PROJECT)
                }
            }
            post {
                failure {
                    script {
                        failed_stage = "build image"
                    }
                }
            }
        }
        stage("push image"){
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        container.push("${BUILD_NUMBER}")
                    }
                }
            }
            post {
                failure {
                    script {
                        failed_stage = "push image"
                    }
                }
            }
        }
        stage("clean") {
            steps {
                echo 'for image in \$(sudo docker images | grep ${env.PROJECT} | awk \'{print \$3}\'| uniq); do sudo docker rmi -f \$image; done'
                sh 'for image in \$(sudo docker images | grep ${env.PROJECT} | awk \'{print \$3}\'| uniq); do sudo docker rmi -f \$image; done'
            }
            post {
                failure {
                    script {
                        failed_stage = "clean"
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                mail to: 'carlos.lizalda1@gmail.com',
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL} on ${failed_stage} stage"
            }
        }
    }
}