pipeline {
    agent any
    environment {
        HOME = '.'
        container = null
        PROJECT = "zeronetdev/rampup-back"
    }
    stages {
        stage("test"){
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'npm install'
                sh 'npm test'
                junit '**/test-results.xml'
            }
        }
        stage("build back image"){
            steps {
                script {
                    container = docker.build(PROJECT)
                }
            }
        }
        stage("push image"){
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        container.push("${BUILD_NUMBER}")
                    }
                }
            }
        }
        stage("clean") {
            steps {
                sh 'for image in \$(sudo docker images | grep ${env.PROJECT} | awk \'{print \$3}\'| uniq); do sudo docker rmi -f \$image; done'
            }
        }
    }
    post {
        failure {
            mail to: 'carlos.lizalda1@gmail.com',
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}